from django.test import TestCase
from django.contrib.auth import get_user_model


class CustomUserModelTests(TestCase):
    """Tests for the CustomUser model."""

    def setUp(self):
        self.User = get_user_model()

    def test_create_user_with_email_and_username(self):
        """Test creating a user with email and username succeeds."""
        user = self.User.objects.create_user(
            username="testuser",
            email="testuser@example.com",
            password="testpass123",
        )
        self.assertEqual(user.username, "testuser")
        self.assertEqual(user.email, "testuser@example.com")
        self.assertTrue(user.is_active)
        self.assertFalse(user.is_staff)
        self.assertFalse(user.is_superuser)

    def test_create_user_without_email(self):
        """Test creating a user without an email (email is blank=True by default)."""
        user = self.User.objects.create_user(
            username="noemailuser",
            password="testpass123",
        )
        self.assertEqual(user.email, "")
        self.assertEqual(user.username, "noemailuser")

    def test_create_superuser(self):
        """Test creating a superuser with all privileges."""
        admin_user = self.User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="adminpass123",
        )
        self.assertEqual(admin_user.username, "admin")
        self.assertEqual(admin_user.email, "admin@example.com")
        self.assertTrue(admin_user.is_active)
        self.assertTrue(admin_user.is_staff)
        self.assertTrue(admin_user.is_superuser)

    def test_user_str_returns_email_when_set(self):
        """Test __str__ returns the email when email is set."""
        user = self.User.objects.create_user(
            username="strtest",
            email="strtest@example.com",
            password="testpass123",
        )
        self.assertEqual(str(user), "strtest@example.com")

    def test_user_str_returns_empty_string_when_email_blank(self):
        """
        Test __str__ returns empty string when email is blank.

        This is a known limitation: the model's __str__ returns self.email,
        which is an empty string when no email is provided. This could be
        improved to fall back to username.
        """
        user = self.User.objects.create_user(
            username="blankemailuser",
            password="testpass123",
        )
        # email field defaults to "" (blank string)
        self.assertEqual(str(user), "")

    def test_email_field_is_optional(self):
        """Test that the email field is optional (blank=True)."""
        field = self.User._meta.get_field("email")
        self.assertTrue(field.blank)

    def test_user_creation_with_allauth_signup_fields(self):
        """
        Test that a user can be created with only the fields
        configured in ACCOUNT_SIGNUP_FIELDS (email, password1).
        Username is auto-generated by allauth when ACCOUNT_LOGIN_METHODS={'email'}.
        """
        user = self.User.objects.create_user(
            username="allauthuser",
            email="allauth@example.com",
            password="securepass123",
        )
        self.assertIsNotNone(user.pk)
        self.assertEqual(user.email, "allauth@example.com")


class CustomUserCreationFormTests(TestCase):
    """Tests for the CustomUserCreationForm."""

    def test_form_has_correct_fields(self):
        """Test that the form includes email and username fields."""
        from .forms import CustomUserCreationForm

        form = CustomUserCreationForm()
        self.assertIn("email", form.fields)
        self.assertIn("username", form.fields)

    def test_form_valid_data_creates_user(self):
        """Test that valid form data creates a user."""
        from .forms import CustomUserCreationForm

        form = CustomUserCreationForm(
            data={
                "username": "newuser",
                "email": "newuser@example.com",
                "password1": "complexpassword123",
                "password2": "complexpassword123",
            }
        )
        self.assertTrue(form.is_valid())
        user = form.save()
        self.assertEqual(user.username, "newuser")
        self.assertEqual(user.email, "newuser@example.com")

    def test_form_invalid_with_mismatched_passwords(self):
        """Test that the form is invalid when passwords don't match."""
        from .forms import CustomUserCreationForm

        form = CustomUserCreationForm(
            data={
                "username": "newuser",
                "email": "newuser@example.com",
                "password1": "password123",
                "password2": "differentpassword",
            }
        )
        self.assertFalse(form.is_valid())
        self.assertIn("password2", form.errors)


class CustomUserChangeFormTests(TestCase):
    """Tests for the CustomUserChangeForm."""

    def setUp(self):
        self.User = get_user_model()
        self.user = self.User.objects.create_user(
            username="changeuser",
            email="changeuser@example.com",
            password="testpass123",
        )

    def test_form_has_correct_fields(self):
        """Test that the form includes email and username fields."""
        from .forms import CustomUserChangeForm

        form = CustomUserChangeForm(instance=self.user)
        self.assertIn("email", form.fields)
        self.assertIn("username", form.fields)

    def test_form_updates_email(self):
        """Test that the form can update a user's email."""
        from .forms import CustomUserChangeForm

        form = CustomUserChangeForm(
            data={
                "username": "changeuser",
                "email": "updated@example.com",
            },
            instance=self.user,
        )
        self.assertTrue(form.is_valid())
        form.save()
        self.user.refresh_from_db()
        self.assertEqual(self.user.email, "updated@example.com")
