# Generated by Django 6.0.4 on 2026-08-03 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("availability", models.CharField(blank=True, max_length=50)),
                ("cost", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Metatype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("body_mod", models.IntegerField(default=0)),
                ("agility_mod", models.IntegerField(default=0)),
                ("reaction_mod", models.IntegerField(default=0)),
                ("strength_mod", models.IntegerField(default=0)),
                ("willpower_mod", models.IntegerField(default=0)),
                ("logic_mod", models.IntegerField(default=0)),
                ("intuition_mod", models.IntegerField(default=0)),
                ("charisma_mod", models.IntegerField(default=0)),
                ("edge_mod", models.IntegerField(default=0)),
                ("essence_mod", models.IntegerField(default=0)),
                ("body_max", models.IntegerField(default=6)),
                ("agility_max", models.IntegerField(default=6)),
                ("reaction_max", models.IntegerField(default=6)),
                ("strength_max", models.IntegerField(default=6)),
                ("willpower_max", models.IntegerField(default=6)),
                ("logic_max", models.IntegerField(default=6)),
                ("intuition_max", models.IntegerField(default=6)),
                ("charisma_max", models.IntegerField(default=6)),
                ("edge_max", models.IntegerField(default=6)),
                ("essence_max", models.IntegerField(default=6)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Quality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "quality_type",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        max_length=20,
                    ),
                ),
                ("karma_cost", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("body_mod", models.IntegerField(default=0)),
                ("agility_mod", models.IntegerField(default=0)),
                ("reaction_mod", models.IntegerField(default=0)),
                ("strength_mod", models.IntegerField(default=0)),
                ("willpower_mod", models.IntegerField(default=0)),
                ("logic_mod", models.IntegerField(default=0)),
                ("intuition_mod", models.IntegerField(default=0)),
                ("charisma_mod", models.IntegerField(default=0)),
                ("edge_mod", models.IntegerField(default=0)),
                ("essence_mod", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "spell_type",
                    models.CharField(
                        choices=[
                            ("combat", "Combat"),
                            ("detection", "Detection"),
                            ("health", "Health"),
                            ("illusion", "Illusion"),
                            ("manipulation", "Manipulation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("drain", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alias", models.CharField(blank=True, max_length=100)),
                (
                    "metatype_name",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("elf", "Elf"),
                            ("ork", "Ork"),
                            ("dwarf", "Dwarf"),
                            ("troll", "Troll"),
                        ],
                        default="human",
                        max_length=20,
                    ),
                ),
                (
                    "magic_type",
                    models.CharField(
                        choices=[
                            ("mundane", "Mundane"),
                            ("adept", "Adept"),
                            ("magician", "Magician"),
                            ("mystic_adept", "Mystic Adept"),
                            ("technomancer", "Technomancer"),
                        ],
                        default="mundane",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.IntegerField(default=1)),
                ("agility", models.IntegerField(default=1)),
                ("reaction", models.IntegerField(default=1)),
                ("strength", models.IntegerField(default=1)),
                ("willpower", models.IntegerField(default=1)),
                ("logic", models.IntegerField(default=1)),
                ("intuition", models.IntegerField(default=1)),
                ("charisma", models.IntegerField(default=1)),
                ("edge", models.IntegerField(default=1)),
                ("essence", models.IntegerField(default=6)),
                ("karma", models.IntegerField(default=0)),
                ("nuyen", models.IntegerField(default=0)),
                ("magic", models.IntegerField(default=0)),
                ("resonance", models.IntegerField(default=0)),
                ("background", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CharacterGear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "gear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.gear",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "gear")},
            },
        ),
        migrations.AddField(
            model_name="character",
            name="gear",
            field=models.ManyToManyField(
                related_name="characters",
                through="characters.CharacterGear",
                to="characters.gear",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="metatype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="characters.metatype",
            ),
        ),
        migrations.CreateModel(
            name="CharacterQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "quality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.quality",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "quality")},
            },
        ),
        migrations.AddField(
            model_name="character",
            name="qualities",
            field=models.ManyToManyField(
                related_name="characters",
                through="characters.CharacterQuality",
                to="characters.quality",
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("knowledge", "Knowledge"),
                            ("language", "Language"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("linked_attribute", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_specialization", models.BooleanField(default=False)),
                (
                    "parent_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="characters.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("is_specialization", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "skill")},
            },
        ),
        migrations.AddField(
            model_name="character",
            name="skills",
            field=models.ManyToManyField(
                related_name="characters",
                through="characters.CharacterSkill",
                to="characters.skill",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="spells",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="characters.spell"
            ),
        ),
    ]
