# Generated by Django 6.0.4 on 2026-08-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactergear",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_gear",
                to="characters.character",
            ),
        ),
        migrations.AlterField(
            model_name="characterquality",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_qualities",
                to="characters.character",
            ),
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_skills",
                to="characters.character",
            ),
        ),
    ]
