# Generated by Django 6.0.4 on 2026-07-29 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdeptPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "activation_type",
                    models.CharField(
                        choices=[
                            ("always", "Always On"),
                            ("simple", "Simple Action"),
                            ("free", "Free Action"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost_per_rank",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Power points per rank",
                        max_digits=4,
                    ),
                ),
                ("max_rank", models.IntegerField(default=6)),
                ("description", models.TextField()),
                ("prerequisites", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("armor_rating", models.IntegerField()),
                ("social_penalty", models.IntegerField(default=0)),
                ("availability", models.CharField(blank=True, max_length=50)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "capacity",
                    models.IntegerField(default=0, help_text="Modification capacity"),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bioware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("essence_cost", models.DecimalField(decimal_places=2, max_digits=4)),
                ("availability", models.CharField(blank=True, max_length=50)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("alpha", "Alpha"),
                            ("beta", "Beta"),
                            ("delta", "Delta"),
                            ("used", "Used"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("stats", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Cyberware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("essence_cost", models.DecimalField(decimal_places=2, max_digits=4)),
                ("availability", models.CharField(blank=True, max_length=50)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("alpha", "Alpha"),
                            ("beta", "Beta"),
                            ("delta", "Delta"),
                            ("used", "Used"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("stats", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Gear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("electronics", "Electronics"),
                            ("survival", "Survival Gear"),
                            ("tools", "Tools"),
                            ("drugs", "Drugs"),
                            ("vehicles", "Vehicles"),
                            ("drones", "Drones"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True, help_text="Availability rating", max_length=50
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("legality", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Game statistics in JSON format",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MagicType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("mundane", "Mundane"),
                            ("adept", "Adept"),
                            ("magician", "Magician"),
                            ("aspected", "Aspected Magician"),
                            ("mystic_adept", "Mystic Adept"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("magic_max", models.IntegerField(default=6)),
                ("resonance_available", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Metatype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("elf", "Elf"),
                            ("dwarf", "Dwarf"),
                            ("ork", "Ork"),
                            ("troll", "Troll"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("body_min", models.IntegerField(default=1)),
                ("body_max", models.IntegerField(default=6)),
                ("agility_min", models.IntegerField(default=1)),
                ("agility_max", models.IntegerField(default=6)),
                ("reaction_min", models.IntegerField(default=1)),
                ("reaction_max", models.IntegerField(default=6)),
                ("strength_min", models.IntegerField(default=1)),
                ("strength_max", models.IntegerField(default=6)),
                ("willpower_min", models.IntegerField(default=1)),
                ("willpower_max", models.IntegerField(default=6)),
                ("logic_min", models.IntegerField(default=1)),
                ("logic_max", models.IntegerField(default=6)),
                ("intuition_min", models.IntegerField(default=1)),
                ("intuition_max", models.IntegerField(default=6)),
                ("charisma_min", models.IntegerField(default=1)),
                ("charisma_max", models.IntegerField(default=6)),
                ("edge_min", models.IntegerField(default=1)),
                ("edge_max", models.IntegerField(default=6)),
                (
                    "essence_max",
                    models.DecimalField(decimal_places=1, default=6.0, max_digits=3),
                ),
                (
                    "special_attributes",
                    models.TextField(
                        blank=True,
                        help_text="Special metatype attributes like Thermographic Vision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metatype",
                "verbose_name_plural": "Metatypes",
            },
        ),
        migrations.CreateModel(
            name="Quality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        max_length=10,
                    ),
                ),
                (
                    "karmic_cost",
                    models.IntegerField(
                        help_text="Karma cost (positive) or bonus (negative)"
                    ),
                ),
                ("max_rank", models.IntegerField(default=1)),
                ("description", models.TextField()),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True, help_text="Any prerequisites for this quality"
                    ),
                ),
                (
                    "effects",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Game mechanics effects in JSON format",
                    ),
                ),
            ],
            options={
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("combat", "Combat"),
                            ("physical", "Physical"),
                            ("social", "Social"),
                            ("technical", "Technical"),
                            ("vehicle", "Vehicle"),
                            ("magic", "Magic"),
                            ("resonance", "Resonance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_knowledge_skill", models.BooleanField(default=False)),
                ("is_language", models.BooleanField(default=False)),
                (
                    "linked_attribute",
                    models.CharField(
                        help_text="Primary attribute linked to this skill",
                        max_length=20,
                    ),
                ),
                (
                    "default_attribute",
                    models.CharField(
                        blank=True,
                        help_text="Default attribute if not trained",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("combat", "Combat"),
                            ("detection", "Detection"),
                            ("health", "Health"),
                            ("illusion", "Illusion"),
                            ("manipulation", "Manipulation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "spell_type",
                    models.CharField(
                        choices=[("physical", "Physical"), ("mana", "Mana")],
                        max_length=10,
                    ),
                ),
                (
                    "range",
                    models.CharField(
                        choices=[
                            ("touch", "Touch"),
                            ("los", "Line of Sight"),
                            ("los_a", "Line of Sight (Area)"),
                            ("personal", "Personal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("sustained", "Sustained"),
                            ("permanent", "Permanent"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "drain_code",
                    models.CharField(help_text="Drain value like F-2", max_length=10),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("blade", "Blade"),
                            ("club", "Club"),
                            ("exotic_melee", "Exotic Melee"),
                            ("pistol", "Pistol"),
                            ("smg", "Submachine Gun"),
                            ("assault_rifle", "Assault Rifle"),
                            ("shotgun", "Shotgun"),
                            ("sniper_rifle", "Sniper Rifle"),
                            ("heavy_weapon", "Heavy Weapon"),
                            ("bow", "Bow/Crossbow"),
                            ("thrown", "Thrown Weapon"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accuracy", models.IntegerField()),
                (
                    "damage",
                    models.CharField(
                        help_text="Damage value like 6P or 8S", max_length=20
                    ),
                ),
                ("armor_penetration", models.IntegerField(default=0)),
                (
                    "attack_rating",
                    models.IntegerField(
                        blank=True, help_text="For melee attacks", null=True
                    ),
                ),
                (
                    "defense_rating",
                    models.IntegerField(
                        blank=True, help_text="For melee attacks", null=True
                    ),
                ),
                (
                    "reach",
                    models.IntegerField(default=0, help_text="For melee weapons"),
                ),
                ("concealability", models.IntegerField(default=0)),
                ("availability", models.CharField(blank=True, max_length=50)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterAdeptPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(default=1)),
                (
                    "power_points_spent",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                (
                    "adept_power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shadowrun_char.adeptpower",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                (
                    "quality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shadowrun_char.quality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShadowrunCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alias", models.CharField(blank=True, max_length=100)),
                (
                    "body",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "agility",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "reaction",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "willpower",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "logic",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "intuition",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "charisma",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "edge",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "magic",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "resonance",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "essence",
                    models.DecimalField(
                        decimal_places=1,
                        default=6.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(6.0),
                        ],
                    ),
                ),
                (
                    "initiative_physical",
                    models.IntegerField(
                        default=0, help_text="Physical initiative dice"
                    ),
                ),
                (
                    "initiative_matrix",
                    models.IntegerField(default=0, help_text="Matrix initiative dice"),
                ),
                (
                    "initiative_astral",
                    models.IntegerField(default=0, help_text="Astral initiative dice"),
                ),
                (
                    "physical_track",
                    models.IntegerField(help_text="Physical damage track boxes"),
                ),
                (
                    "stun_track",
                    models.IntegerField(help_text="Stun damage track boxes"),
                ),
                ("total_karma", models.IntegerField(default=0)),
                ("current_karma", models.IntegerField(default=0)),
                (
                    "nuyen",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("age", models.IntegerField(default=25)),
                ("height", models.CharField(blank=True, max_length=20)),
                ("weight", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("background", models.TextField(blank=True)),
                ("character_concept", models.CharField(blank=True, max_length=200)),
                ("is_created", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adept_powers",
                    models.ManyToManyField(
                        through="shadowrun_char.CharacterAdeptPower",
                        to="shadowrun_char.adeptpower",
                    ),
                ),
                (
                    "armor",
                    models.ManyToManyField(blank=True, to="shadowrun_char.armor"),
                ),
                ("gear", models.ManyToManyField(blank=True, to="shadowrun_char.gear")),
                (
                    "magic_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shadowrun_char.magictype",
                    ),
                ),
                (
                    "metatype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shadowrun_char.metatype",
                    ),
                ),
                (
                    "qualities",
                    models.ManyToManyField(
                        through="shadowrun_char.CharacterQuality",
                        to="shadowrun_char.quality",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadowrun_characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shadowrun Character",
                "verbose_name_plural": "Shadowrun Characters",
            },
        ),
        migrations.CreateModel(
            name="Lifestyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "lifestyle_type",
                    models.CharField(
                        choices=[
                            ("street", "Street"),
                            ("squatter", "Squatter"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monthly_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("security_rating", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifestyles",
                        to="shadowrun_char.shadowruncharacter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("archetype", models.CharField(blank=True, max_length=100)),
                (
                    "connection_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "loyalty_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_fixer", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="shadowrun_char.shadowruncharacter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ]
                    ),
                ),
                ("specialization", models.CharField(blank=True, max_length=100)),
                (
                    "specialization_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("specialization", "Specialization"),
                            ("expertise", "Expertise"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shadowrun_char.shadowruncharacter",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shadowrun_char.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "skill", "specialization")},
            },
        ),
        migrations.AddField(
            model_name="characterquality",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shadowrun_char.shadowruncharacter",
            ),
        ),
        migrations.CreateModel(
            name="CharacterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("session", "Session Log"),
                            ("character_development", "Character Development"),
                            ("karma", "Karma Change"),
                            ("nuyen", "Nuyen Change"),
                            ("note", "General Note"),
                        ],
                        default="note",
                        max_length=21,
                    ),
                ),
                ("karma_change", models.IntegerField(default=0)),
                (
                    "nuyen_change",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="shadowrun_char.shadowruncharacter",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="characteradeptpower",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shadowrun_char.shadowruncharacter",
            ),
        ),
        migrations.AddField(
            model_name="shadowruncharacter",
            name="skills",
            field=models.ManyToManyField(
                through="shadowrun_char.CharacterSkill", to="shadowrun_char.skill"
            ),
        ),
        migrations.AddField(
            model_name="shadowruncharacter",
            name="spells",
            field=models.ManyToManyField(blank=True, to="shadowrun_char.spell"),
        ),
        migrations.AddField(
            model_name="shadowruncharacter",
            name="weapons",
            field=models.ManyToManyField(blank=True, to="shadowrun_char.weapon"),
        ),
        migrations.AlterUniqueTogether(
            name="characterquality",
            unique_together={("character", "quality")},
        ),
        migrations.CreateModel(
            name="CharacterCyberware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=1)),
                (
                    "essence_cost_total",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "cyberware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shadowrun_char.cyberware",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shadowrun_char.shadowruncharacter",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "cyberware")},
            },
        ),
        migrations.CreateModel(
            name="CharacterBioware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=1)),
                (
                    "essence_cost_total",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "bioware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shadowrun_char.bioware",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shadowrun_char.shadowruncharacter",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "bioware")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="characteradeptpower",
            unique_together={("character", "adept_power")},
        ),
    ]
