# Generated by Django 6.0.4 on 2026-07-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadowrun_char", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterlog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("session", "Session Log"),
                    ("character_development", "Character Development"),
                    ("karma", "Karma Change"),
                    ("nuyen", "Nuyen Change"),
                    ("note", "General Note"),
                ],
                default="note",
                max_length=50,
            ),
        ),
    ]
